### ISSUE TITLE
One error wont go away

### ISSUE THREAD

**Issue by sudokit** [pherrymason/c3-lsp#89] opened 2024-12-01 21:48 UTC
**Describe the bug**
It seems like c3lsp cant live without atleast one error. When i have 2 errors, fix both of them, the latest one stays even though the code is deleted.

**To Reproduce**
1. write any code
2. add an line that introduces an error
3. remove the error line
4. the error remains

**Expected behavior**
The error should disapear

**Screenshots**
![kuva](https://github.com/user-attachments/assets/d15fdc19-5996-48ef-904c-dd1d2006f2e2)
![kuva](https://github.com/user-attachments/assets/2636becf-8dbe-444f-bbdb-3d1bccfef4b2)

**Desktop (please complete the following information):**
 - OS: Windows
![kuva](https://github.com/user-attachments/assets/81c00459-031e-415a-906b-f82c3c18f355)
 - Editor VSCode
 ```
1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64
```
 - Version:
c3lps: latest vscode version
c3c: latest git
```
C3 Compiler Version:       0.6.5 (Pre-release, Dec  1 2024 02:11:39)
Installed directory:       C:/Users/sudokit/Documents/langs/c3c/build/Release/
Git Hash:                  462322026f1d38dba7c968e8c5f5c22617bfc05c
Backends:                  LLVM
LLVM version:              18.1.8
LLVM default target:       x86_64-pc-windows-msvc
```
**Additional context**
Probably related to #59

**Comment by sudokit** [comment] 2024-12-01 22:10
I guess its caused because here [code](https://github.com/pherrymason/c3-lsp/blob/493f23064efeb6a98733b62b9d7579728b2c6294/server/internal/lsp/server/Diagnostics.go#L22) error isnt nil. the output prints: ```2024/12/02 00:05:16 An error: exit status 1```. idk why tho

**Comment by pherrymason** [comment] 2024-12-02 07:35
I suspect is the handling of file paths in Windows as I can't reproduce this in Mac.
Are you able to attach last lines of the lsp log when error is fixed in the editor?

**Comment by pherrymason** [comment] 2024-12-03 14:23
Could you share another log just after a new error is displayed? 
I will compare paths format.

**Comment by sudokit** [comment] 2024-12-03 15:11
Heres the log of typing invalid code, saving file, deleting invalid code and saving file:
```
2024/12/03 17:10:55.982  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":0,"line":17},"start":{"character":0,"line":17}},"rangeLength":0,"text":"a"}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":10}}
2024/12/03 17:10:56.123  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":1,"line":17},"start":{"character":1,"line":17}},"rangeLength":0,"text":"s"}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":11}}
2024/12/03 17:10:56.176  DEBUG [C3-LSP:rpc] jsonrpc2: --> request #4: textDocument/completion: {"context":{"triggerKind":1},"position":{"character":2,"line":17},"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3"}}
2024/12/03 17:10:56.177  DEBUG [C3-LSP.parser] building completion list: "as"
2024/12/03 17:10:56.177  DEBUG [C3-LSP:rpc] jsonrpc2: <-- result #4: textDocument/completion: [{"label":"asm","kind":14},{"label":"assert","kind":14}]
2024/12/03 17:10:56.177  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":2,"line":17},"start":{"character":2,"line":17}},"rangeLength":0,"text":"d"}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":12}}
2024/12/03 17:10:56.407  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":3,"line":17},"start":{"character":3,"line":17}},"rangeLength":0,"text":"a"}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":13}}
2024/12/03 17:10:56.507  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":4,"line":17},"start":{"character":4,"line":17}},"rangeLength":0,"text":"s"}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":14}}
2024/12/03 17:10:56.554  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":5,"line":17},"start":{"character":5,"line":17}},"rangeLength":0,"text":"d"}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":15}}
2024/12/03 17:10:56.739  DEBUG [C3-LSP:rpc] jsonrpc2: --> request #5: textDocument/completion: {"context":{"triggerKind":1},"position":{"character":6,"line":17},"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3"}}
2024/12/03 17:10:56.740  DEBUG [C3-LSP.parser] building completion list: "asdasd"
2024/12/03 17:10:56.740  DEBUG [C3-LSP:rpc] jsonrpc2: <-- result #5: textDocument/completion: null
2024/12/03 17:10:57.304  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didSave: {"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3"}}
2024/12/03 17:10:57.529  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: workspace/didChangeWatchedFiles: {"changes":[{"type":2,"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3"}]}
2024/12/03 17:10:59 output: 
2024/12/03 17:10:59 output: Error|C:/Users/sudokit/Documents/Projects/test/src/main.c3|17|2|Expected a type here.

2024/12/03 17:10:59 An error: exit status 1
2024/12/03 17:10:59.374  DEBUG [C3-LSP:rpc] jsonrpc2: <-- notif: textDocument/publishDiagnostics: {"uri":"file:///C:/Users/sudokit/Documents/Projects/test/src/main.c3","diagnostics":[{"range":{"start":{"line":16,"character":1},"end":{"line":16,"character":99}},"severity":1,"source":"c3c build --test","message":"Expected a type here.\r"}]}
2024/12/03 17:11:18.566  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":0,"line":17},"start":{"character":0,"line":16}},"rangeLength":9,"text":""}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":16}}
2024/12/03 17:11:18.750  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didChange: {"contentChanges":[{"range":{"end":{"character":0,"line":17},"start":{"character":0,"line":16}},"rangeLength":8,"text":""}],"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3","version":17}}
2024/12/03 17:11:19.580  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didSave: {"textDocument":{"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3"}}
2024/12/03 17:11:19.921  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: workspace/didChangeWatchedFiles: {"changes":[{"type":2,"uri":"file:///c%3A/Users/sudokit/Documents/Projects/test/src/main.c3"}]}
2024/12/03 17:11:23 output: 
2024/12/03 17:11:23 output: 
2024/12/03 17:11:23.035  DEBUG [C3-LSP:rpc] jsonrpc2: <-- notif: textDocument/publishDiagnostics: {"uri":"C:/Users/sudokit/Documents/Projects/test/src/main.c3","diagnostics":[]}
```

**Comment by pherrymason** [comment] 2024-12-04 05:01
Could you try this https://github.com/pherrymason/c3-lsp/actions/runs/12147202612/artifacts/2269628742 and see if it fixes this issue? (It's a zip with linux, mac and windows builds)

**Comment by sudokit** [comment] 2024-12-04 15:21
Eyy that does indeed seem to fix it! Now the one error goes away and i can finally get error free code :p. Thank you so much!

**Closed** 2024-12-04 16:01 UTC
Labels: bug
