### ISSUE TITLE
Misidentifies field as std function

### ISSUE THREAD

**Issue by Caleb-o** [pherrymason/c3-lsp#77] opened 2024-09-19 06:11 UTC
**Describe the bug**
Field is misidentified as a std lib function, since it has the same name.

Note: Print seems to have a space before `x` in its signature. 

**To Reproduce**
1. Create a struct
2. Create a field named `print`

**Expected behavior**
Show the field information

**Screenshots**
![image](https://github.com/user-attachments/assets/42f16e84-3e66-4d55-8b3b-e281822f37eb)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Editor: VS Code
 - Version: main - [df7f7ea](https://github.com/pherrymason/c3-lsp/commit/df7f7ea8ab732289a130ca13631e3551f9a91dc5)

**Comment by pherrymason** [comment] 2024-09-24 10:54
@Caleb-o can you provide the full file content where this code is located? I cannot reproduce it in my tests.

**Comment by Caleb-o** [comment] 2024-09-24 10:58
I just tried it again. It seems to be in specific cases of nested structures while importing a module:
```c++
// Needs to include std::io
import std::io;

struct Foo {
  // Needs to be an inner struct or union
  struct data {
    int print;
  }
}

fn void main() {
  // ...
}
```

**Comment by pherrymason** [comment] 2024-09-25 06:56
@Caleb-o , just pushed a fix to better handle these scenarios. In my tests, hover already displays the proper information.

However, autocompletion is not able to find members of that substruct yet. Working on it.

**Comment by pherrymason** [comment] 2024-09-25 07:11
Fixed the hover too.

**Comment by Caleb-o** [comment] 2024-09-25 08:30
> Ok, anonymous structs inside structs are not being properly indexed, that's why. Will work on parsing it properly.
> 
> How do you write/read `print`?
> 
> Like this?
> 
> ```
> Foo obj;
> obj.data.print = 3;
> ```

Yeah, that's it
```
  Foo foo = { { 10 } };
  foo.data.print = 30;
  io::printfn("Print %s", foo.data.print);
```

**Comment by Caleb-o** [comment] 2024-09-25 08:32
This seems to be working now, after pulling the latest changes

**Comment by pherrymason** [comment] 2024-09-25 08:43
I'll close then. Feel free to reopen if you find something still not working.

**Closed by pherrymason** 2024-09-25 08:43 UTC
Labels: bug
